# Generated by Django 4.0.1 on 2022-12-20 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorpIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('ModifyDate', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('CreatorUserName', models.CharField(blank=True, max_length=150, null=True, verbose_name='ایجاد کننده')),
                ('ModifierUserName', models.CharField(blank=True, max_length=150, null=True, verbose_name='ویرایش کننده')),
                ('Version', models.CharField(blank=True, max_length=50, null=True, verbose_name='نسخه')),
                ('CorpCode', models.CharField(max_length=50, verbose_name='کد شرکت')),
                ('CorpName', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام شرکت')),
                ('User', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام کاربر ')),
                ('RequestDate', models.DateField(verbose_name='تاریخ درخواست')),
                ('RequestFor', models.IntegerField(blank=True, choices=[(1, 'پشتیبانی'), (2, 'تست'), (3, 'تولید')], null=True, verbose_name='درخواست مربوط به ')),
                ('Importance', models.IntegerField(blank=True, choices=[(1, 'اهمیت کم'), (2, 'اهمیت متوسط'), (3, 'اهمیت بالا')], null=True, verbose_name='اهمیت')),
                ('Priority', models.IntegerField(blank=True, choices=[(1, 'اولویت کم'), (2, 'اولویت متوسط'), (3, 'اولویت بالا')], null=True, verbose_name='اولویت')),
            ],
            options={
                'verbose_name': 'درخواست پاسخ گویی هر تیم به صورت حساب ',
                'verbose_name_plural': 'درخواست پاسخ گویی تیم ها به صورت حساب ها',
            },
        ),
        migrations.CreateModel(
            name='CorpIssueConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=2000, null=True, verbose_name='توضیحات')),
                ('CommentDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('CommentUser', models.CharField(max_length=100, null=True, verbose_name='کاربر ارسال کننده پیام')),
                ('User_type', models.IntegerField(choices=[(1, 'مدیر واحد فروش '), (2, 'مدیر تیم ها')], null=True, verbose_name='نوع کاربر')),
                ('IsLock', models.BooleanField(default=False)),
                ('CorpIssue', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.corpissue', verbose_name='درخواست')),
            ],
            options={
                'verbose_name': ' جزئیات درخواست پاسخ گویی هر تیم به صورت حساب ',
                'verbose_name_plural': ' جزئیات درخواست پاسخ گویی تیم ها به صورت حساب ها',
            },
        ),
        migrations.CreateModel(
            name='CorpIssueDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('CorpIssueDetailDescription', models.CharField(max_length=2000, null=True, verbose_name='توضیحات')),
                ('TeamCode', models.CharField(max_length=50, verbose_name='تیم')),
                ('WorkHours', models.CharField(blank=True, max_length=100, null=True, verbose_name='ساعت کارکرد')),
                ('Reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='دلیل')),
                ('FinishDate', models.DateField(blank=True, null=True, verbose_name='تاریخ زمان پاسخ به درخواست')),
                ('Result', models.CharField(blank=True, max_length=4000, null=True, verbose_name='نتیجه تیم')),
                ('TaskNumber', models.IntegerField(null=True, verbose_name='شماره تسک مورد نظر')),
                ('DocumentId', models.IntegerField(null=True, verbose_name='شماره داکیومنت ایجاد شده در پرتال')),
                ('State', models.IntegerField(choices=[(1, 'اظهار نظر واحد فروش'), (2, ' اظهار نظر مدیر تیم'), (3, 'خاتمه درخواست')], default=1, verbose_name='حالت و وضعیت درخواست مورد نظر')),
                ('CorpIssue', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.corpissue', verbose_name='درخواست')),
            ],
        ),
        migrations.CreateModel(
            name='CorpIssueFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=200, null=True)),
                ('File', models.FileField(blank=True, null=True, upload_to='media/corp_issue_file')),
                ('CorpIssueConversation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.corpissueconversation', verbose_name=' مکالمات درخواست')),
                ('CorpIssueDetail', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.corpissuedetail', verbose_name=' جزئیات درخواست')),
            ],
        ),
        migrations.AddField(
            model_name='corpissueconversation',
            name='CorpIssueDetail',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.corpissuedetail', verbose_name=' جزئیات درخواست'),
        ),
        migrations.CreateModel(
            name='ConstValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=50, verbose_name='عنوان')),
                ('Code', models.CharField(max_length=100, verbose_name='کد')),
                ('IsActive', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('OrderNumber', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='شماره ترتیب')),
                ('ConstValue', models.IntegerField(blank=True, null=True, verbose_name='مقدار مربوطه')),
                ('Parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.constvalue', verbose_name='شناسه پدر')),
            ],
            options={
                'verbose_name': 'مقدار ثابت',
                'verbose_name_plural': 'مقادیر ثابت',
                'ordering': ['Parent_id', 'OrderNumber'],
            },
        ),
    ]
