# Generated by Django 4.0.1 on 2023-01-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorpIssue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VersionNumber', models.CharField(max_length=50)),
                ('CorpCode', models.CharField(max_length=3, verbose_name='کد شرکت بیمه')),
                ('CorpName', models.CharField(max_length=50, verbose_name='نام شرکت بیمه')),
                ('RequestDate', models.DateField(verbose_name='تاریخ درخواست')),
                ('TeamCode', models.CharField(max_length=3, verbose_name='کد تیم ')),
                ('FinishDate', models.DateField(verbose_name='تاریخ اتمام درخواست')),
                ('State', models.IntegerField(verbose_name='حالت و وضعیت درخواست مورد نظر')),
                ('Title', models.CharField(max_length=200, verbose_name='عنوان درخواست')),
                ('TaskNumber', models.IntegerField(null=True, verbose_name='شماره تسک درخواست')),
                ('Result', models.CharField(blank=True, max_length=4000, null=True, verbose_name='نتیجه ')),
                ('WorkHours', models.CharField(blank=True, max_length=50, null=True, verbose_name='ساعت کارکرد')),
                ('Duration', models.CharField(max_length=50, verbose_name='مدت زمانی که این درخواست  تمام شود')),
            ],
            options={
                'verbose_name': 'اطلاعات درخواست ها ',
                'db_table': 'CorpIssue_RequestInformation',
                'managed': False,
            },
        ),
    ]
