# Generated by Django 4.0.1 on 2024-12-08 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CorpIssue', '0002_requestinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMSHBTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Corp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_code', models.CharField(max_length=3)),
                ('corp_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_at', models.DateField(null=True)),
                ('closed_at', models.DateField(null=True)),
                ('corp_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.corp')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_work_hours', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceTaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=50)),
                ('work_hours', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('invoice_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.invoicetask')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_approver', models.CharField(max_length=50)),
                ('sales_manager', models.CharField(max_length=50)),
                ('from_date', models.DateField(auto_now_add=True)),
                ('to_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=50)),
                ('real_work_hours', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.project')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_code', models.CharField(max_length=3)),
                ('team_name', models.CharField(max_length=50)),
                ('manager', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='corpissueconversation',
            name='CorpIssue',
        ),
        migrations.RemoveField(
            model_name='corpissueconversation',
            name='CorpIssueDetail',
        ),
        migrations.RemoveField(
            model_name='corpissuedetail',
            name='CorpIssue',
        ),
        migrations.RemoveField(
            model_name='corpissuefile',
            name='CorpIssueConversation',
        ),
        migrations.RemoveField(
            model_name='corpissuefile',
            name='CorpIssueDetail',
        ),
        migrations.DeleteModel(
            name='RequestInformation',
        ),
        migrations.AlterModelOptions(
            name='constvalue',
            options={},
        ),
        migrations.RemoveField(
            model_name='constvalue',
            name='Caption',
        ),
        migrations.RemoveField(
            model_name='constvalue',
            name='Code',
        ),
        migrations.RemoveField(
            model_name='constvalue',
            name='ConstValue',
        ),
        migrations.RemoveField(
            model_name='constvalue',
            name='IsActive',
        ),
        migrations.RemoveField(
            model_name='constvalue',
            name='OrderNumber',
        ),
        migrations.RemoveField(
            model_name='constvalue',
            name='Parent',
        ),
        migrations.AddField(
            model_name='constvalue',
            name='code',
            field=models.CharField(default='ccc', max_length=50),
        ),
        migrations.AddField(
            model_name='constvalue',
            name='parent_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.constvalue'),
        ),
        migrations.AddField(
            model_name='constvalue',
            name='value',
            field=models.CharField(default='ccc', max_length=50),
        ),
        migrations.DeleteModel(
            name='CorpIssue',
        ),
        migrations.DeleteModel(
            name='CorpIssueConversation',
        ),
        migrations.DeleteModel(
            name='CorpIssueDetail',
        ),
        migrations.DeleteModel(
            name='CorpIssueFile',
        ),
        migrations.AddField(
            model_name='task',
            name='task_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.constvalue'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.team'),
        ),
        migrations.AddField(
            model_name='invoicetaskhistory',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.constvalue'),
        ),
        migrations.AddField(
            model_name='invoicetask',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.constvalue'),
        ),
        migrations.AddField(
            model_name='invoicetask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.task'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.constvalue'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='version_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.version'),
        ),
    ]
