# Generated by Django 5.0.11 on 2025-02-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorpIssue', '0003_pmshbtask_corp_invoice_invoicetask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.CharField(max_length=50),
        ),
    ]
