# Generated by Django 5.0.11 on 2025-02-01 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorpIssue', '0005_alter_invoice_corp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='version_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.version'),
        ),
    ]
