# Generated by Django 5.0.11 on 2025-02-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorpIssue', '0006_alter_invoice_version_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(max_length=300),
        ),
    ]
