# Generated by Django 5.0.11 on 2025-02-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorpIssue', '0007_alter_task_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='real_work_hours',
            field=models.IntegerField(null=True),
        ),
    ]
