# Generated by Django 5.0.11 on 2025-02-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorpIssue', '0008_alter_task_real_work_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetaskhistory',
            name='doc_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
