# Generated by Django 5.0.11 on 2025-02-06 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorpIssue', '0009_alter_invoicetaskhistory_doc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='corp_code',
            field=models.ForeignKey(db_column='corp_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.corp'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='version_number',
            field=models.ForeignKey(db_column='version_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.version'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_code',
            field=models.ForeignKey(db_column='team_code', on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.team'),
        ),
    ]
