# Generated by Django 5.0.11 on 2025-02-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorpIssue', '0010_alter_invoice_corp_code_alter_invoice_version_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='doc_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
