# Generated by Django 5.0.11 on 2025-02-17 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorpIssue', '0011_invoice_doc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(help_text='Explanation provided by the product assistant for rejection')),
                ('rejected_by', models.CharField(default='product_assistant', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(help_text='National code of the person who provided the rejection explanation', max_length=50)),
                ('const_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_explanations', to='CorpIssue.constvalue')),
                ('invoice_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_explanations', to='CorpIssue.invoicetask')),
            ],
        ),
    ]
