# Generated by Django 5.0.11 on 2025-02-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CorpIssue', '0013_remove_invoice_corp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team_code',
        ),
    ]
