# Generated by Django 5.0.11 on 2025-02-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorpIssue', '0014_remove_project_team_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corp',
            name='id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AlterField(
            model_name='corp',
            name='corp_code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
