# Generated by Django 5.0.11 on 2025-02-27 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorpIssue', '0015_remove_corp_id_remove_team_id_alter_corp_corp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='corp_code',
            field=models.ForeignKey(db_column='corp_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.corp'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_code',
            field=models.ForeignKey(db_column='team_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.team'),
        ),
    ]
