# Generated by Django 5.0.11 on 2025-02-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorpIssue', '0017_remove_invoice_version_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='id',
        ),
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
