# Generated by Django 5.0.11 on 2025-02-27 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorpIssue', '0018_remove_version_id_alter_version_version_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='version_number',
            field=models.ForeignKey(db_column='version_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.version'),
        ),
    ]
