# Generated by Django 5.0.11 on 2025-03-30 20:53

import CorpIssue.validator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorpIssue', '0020_task_parent_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constvalue',
            options={'verbose_name': 'مقدار ثابت', 'verbose_name_plural': 'مقادیر ثابت'},
        ),
        migrations.AlterModelOptions(
            name='corp',
            options={'verbose_name': 'شرکت', 'verbose_name_plural': 'شرکت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'صورت حساب', 'verbose_name_plural': 'صورت حساب\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='invoicetask',
            options={'verbose_name': 'تسک صورت حساب', 'verbose_name_plural': 'تسک\u200cهای صورت حساب'},
        ),
        migrations.AlterModelOptions(
            name='invoicetaskhistory',
            options={'verbose_name': 'تاریخچه تسک صورت حساب', 'verbose_name_plural': 'تاریخچه\u200cهای تسک صورت حساب'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='rejectiondetails',
            options={'verbose_name': 'توضیحات رد', 'verbose_name_plural': 'توضیحات رد'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'تنظیمات', 'verbose_name_plural': 'تنظیمات'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'تسک', 'verbose_name_plural': 'تسک\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'تیم', 'verbose_name_plural': 'تیم\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'نسخه', 'verbose_name_plural': 'نسخه\u200cها'},
        ),
        migrations.AlterField(
            model_name='constvalue',
            name='code',
            field=models.CharField(help_text='کد مقدار ثابت را وارد کنید.', max_length=50, verbose_name='کد مقدار ثابت'),
        ),
        migrations.AlterField(
            model_name='constvalue',
            name='parent_code',
            field=models.ForeignKey(blank=True, help_text='کد والد را وارد کنید.', null=True, on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.constvalue', verbose_name='کد والد'),
        ),
        migrations.AlterField(
            model_name='constvalue',
            name='value',
            field=models.CharField(help_text='مقدار ثابت را وارد کنید.', max_length=50, verbose_name='مقدار ثابت'),
        ),
        migrations.AlterField(
            model_name='corp',
            name='corp_code',
            field=models.CharField(help_text='کد منحصر به فرد شرکت را وارد کنید.', max_length=3, primary_key=True, serialize=False, verbose_name='کد شرکت'),
        ),
        migrations.AlterField(
            model_name='corp',
            name='corp_name',
            field=models.CharField(help_text='نام شرکت را وارد کنید.', max_length=50, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='closed_at',
            field=models.DateField(null=True, verbose_name='تاریخ بسته شدن'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='corp_code',
            field=models.ForeignKey(db_column='corp_code', help_text='کد شرکت مربوط به این صورت حساب را وارد کنید.', null=True, on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.corp', verbose_name='کد شرکت'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='doc_id',
            field=models.CharField(blank=True, help_text='شناسه سند مربوط به این صورت حساب را وارد کنید.', max_length=50, null=True, verbose_name='شناسه سند'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='send_at',
            field=models.DateField(null=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(help_text='وضعیت صورت حساب را انتخاب کنید.', on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.constvalue', verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='version_number',
            field=models.ForeignKey(db_column='version_number', help_text='شماره نسخه مربوط به این صورت حساب را وارد کنید.', null=True, on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.version', verbose_name='شماره نسخه'),
        ),
        migrations.AlterField(
            model_name='invoicetask',
            name='invoice',
            field=models.ForeignKey(help_text='صورت حساب مربوط به این تسک را انتخاب کنید.', on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.invoice', verbose_name='صورت حساب'),
        ),
        migrations.AlterField(
            model_name='invoicetask',
            name='invoice_work_hours',
            field=models.IntegerField(help_text='ساعات کار اعلامی را وارد کنید.', validators=[CorpIssue.validator.positive_number_validator], verbose_name='ساعات کار اعلامی'),
        ),
        migrations.AlterField(
            model_name='invoicetask',
            name='status',
            field=models.ForeignKey(help_text='وضعیت تسک را انتخاب کنید.', on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.constvalue', verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='invoicetask',
            name='task',
            field=models.ForeignKey(help_text='تسک مربوط به این صورت حساب را انتخاب کنید.', on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.task', verbose_name='تسک'),
        ),
        migrations.AlterField(
            model_name='invoicetaskhistory',
            name='comment',
            field=models.CharField(blank=True, help_text='توضیحات مربوط به این تاریخچه را وارد کنید.', max_length=200, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='invoicetaskhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='invoicetaskhistory',
            name='created_by',
            field=models.CharField(help_text='کد ملی ایجادکننده را وارد کنید.', max_length=50, verbose_name='ایجاد شده توسط'),
        ),
        migrations.AlterField(
            model_name='invoicetaskhistory',
            name='doc_id',
            field=models.CharField(help_text='شناسه سند مربوط به این تاریخچه را وارد کنید.', max_length=50, null=True, verbose_name='شناسه سند'),
        ),
        migrations.AlterField(
            model_name='invoicetaskhistory',
            name='invoice_task',
            field=models.ForeignKey(help_text='تسک صورت حساب مربوط به این تاریخچه را انتخاب کنید.', on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.invoicetask', verbose_name='تسک صورت حساب'),
        ),
        migrations.AlterField(
            model_name='invoicetaskhistory',
            name='status',
            field=models.ForeignKey(help_text='وضعیت تاریخچه را انتخاب کنید.', on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.constvalue', verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='invoicetaskhistory',
            name='work_hours',
            field=models.IntegerField(help_text='ساعات کار را وارد کنید.', validators=[CorpIssue.validator.positive_number_validator], verbose_name='ساعات کار'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(help_text='نام پروژه را وارد کنید.', max_length=50, verbose_name='نام پروژه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_code',
            field=models.ForeignKey(db_column='team_code', help_text='کد تیم مربوط به این پروژه را وارد کنید.', null=True, on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.team', verbose_name='کد تیم'),
        ),
        migrations.AlterField(
            model_name='rejectiondetails',
            name='const_value',
            field=models.ForeignKey(help_text='مقدار ثابت مربوط به این توضیحات رد را انتخاب کنید.', on_delete=django.db.models.deletion.CASCADE, related_name='rejection_explanations', to='CorpIssue.constvalue', verbose_name='مقدار ثابت'),
        ),
        migrations.AlterField(
            model_name='rejectiondetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاریخ ایجاد این توضیحات رد.', verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='rejectiondetails',
            name='created_by',
            field=models.CharField(help_text='کد ملی فردی که این توضیحات رد را ایجاد کرده است.', max_length=50, validators=[CorpIssue.validator.national_code_validator], verbose_name='ایجاد شده توسط'),
        ),
        migrations.AlterField(
            model_name='rejectiondetails',
            name='explanation',
            field=models.TextField(help_text='توضیحات ارائه شده توسط دستیار محصول برای رد.', verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='rejectiondetails',
            name='invoice_task',
            field=models.ForeignKey(help_text='تسک صورت حساب مربوط به این توضیحات رد را انتخاب کنید.', on_delete=django.db.models.deletion.CASCADE, related_name='rejection_explanations', to='CorpIssue.invoicetask', verbose_name='تسک صورت حساب'),
        ),
        migrations.AlterField(
            model_name='rejectiondetails',
            name='rejected_by',
            field=models.CharField(default='product_assistant', help_text='کد ملی فردی که توضیحات رد را ارائه کرده است.', max_length=50, validators=[CorpIssue.validator.national_code_validator], verbose_name='رد شده توسط'),
        ),
        migrations.AlterField(
            model_name='rejectiondetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='تاریخ آخرین به\u200cروزرسانی این توضیحات رد.', verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='from_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='invoice_approver',
            field=models.CharField(help_text='کد ملی تاییدکننده صورت حساب را وارد کنید.', max_length=50, validators=[CorpIssue.validator.national_code_validator], verbose_name='تاییدکننده صورت حساب'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال است؟'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='sales_manager',
            field=models.CharField(help_text='کد ملی مدیر فروش را وارد کنید.', max_length=50, validators=[CorpIssue.validator.national_code_validator], verbose_name='مدیر فروش'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='to_date',
            field=models.DateField(null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='تسک والد را انتخاب کنید.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_tasks', to='CorpIssue.task', verbose_name='تسک والد'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(help_text='پروژه مربوط به این تسک را انتخاب کنید.', on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.project', verbose_name='پروژه'),
        ),
        migrations.AlterField(
            model_name='task',
            name='real_work_hours',
            field=models.IntegerField(help_text='ساعات کار واقعی را وارد کنید.', null=True, validators=[CorpIssue.validator.positive_number_validator], verbose_name='ساعات کار واقعی'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.BigIntegerField(help_text='شناسه تسک را وارد کنید.', primary_key=True, serialize=False, verbose_name='شناسه تسک'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_kind',
            field=models.ForeignKey(help_text='نوع تسک را انتخاب کنید.', on_delete=django.db.models.deletion.CASCADE, to='CorpIssue.constvalue', verbose_name='نوع تسک'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(help_text='عنوان تسک را وارد کنید.', max_length=300, verbose_name='عنوان تسک'),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.CharField(help_text='کد ملی مدیر تیم را وارد کنید.', max_length=50, validators=[CorpIssue.validator.national_code_validator], verbose_name='کد ملی مدیر'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(help_text='کد منحصر به فرد تیم را وارد کنید.', max_length=3, primary_key=True, serialize=False, verbose_name='کد تیم'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(help_text='نام تیم را وارد کنید.', max_length=50, verbose_name='نام تیم'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.CharField(help_text='شماره نسخه را وارد کنید.', max_length=50, primary_key=True, serialize=False, verbose_name='شماره نسخه'),
        ),
    ]
