# Generated by Django 5.0.11 on 2025-04-12 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorpIssue', '0021_alter_constvalue_options_alter_corp_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectiondetails',
            name='const_value',
            field=models.ForeignKey(help_text='مقدار ثابت مربوط به این توضیحات رد را انتخاب کنید.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejection_explanations', to='CorpIssue.constvalue', verbose_name='مقدار ثابت'),
        ),
        migrations.CreateModel(
            name='InvoiceExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1, verbose_name='شماره نسخه')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('file_path', models.CharField(max_length=255, verbose_name='مسیر فایل')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_versions', to='CorpIssue.invoice', verbose_name='صورت حساب')),
            ],
            options={
                'verbose_name': 'نسخه اکسل',
                'verbose_name_plural': 'نسخه های اکسل',
                'ordering': ['-version_number'],
            },
        ),
    ]
