# Generated by Django 5.0.11 on 2025-04-12 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CorpIssue', '0022_alter_rejectiondetails_const_value_invoiceexcel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceexcel',
            options={'verbose_name': 'نسخه اکسل', 'verbose_name_plural': 'نسخه های اکسل'},
        ),
        migrations.RemoveField(
            model_name='invoiceexcel',
            name='version_number',
        ),
    ]
