# Generated by Django 4.0.1 on 2023-01-04 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamFeature',
            fields=[
                ('CreatorUserName', models.CharField(max_length=150, null=True, verbose_name='ایجاد شده توسط')),
                ('LastModifierUserName', models.CharField(max_length=150, null=True, verbose_name='ویرایش شده توسط')),
                ('CreateDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('ModifyDate', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('Feature', models.CharField(max_length=1000, verbose_name='قابلیت')),
                ('FeatureCode', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, verbose_name='کد ویژگی')),
                ('TeamCode', models.CharField(max_length=3, verbose_name='نام تیم')),
                ('YearNumber', models.PositiveSmallIntegerField(verbose_name='سال')),
                ('FeaturePriority', models.PositiveSmallIntegerField(verbose_name='اولویت ویژگی')),
                ('Importance', models.PositiveSmallIntegerField(choices=[('متوسط', 1), ('بالا', 2), ('خیلی بالا', 3)], default=1, verbose_name='میزان اهمیت')),
            ],
            options={
                'verbose_name': 'قابلیت مهم سیستم',
                'verbose_name_plural': 'قابلیت های مهم سیستم',
                'ordering': ['-CreateDate'],
            },
        ),
        migrations.CreateModel(
            name='TeamFeatureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatorUserName', models.CharField(max_length=150, null=True, verbose_name='ایجاد شده توسط')),
                ('LastModifierUserName', models.CharField(max_length=150, null=True, verbose_name='ویرایش شده توسط')),
                ('CreateDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('ModifyDate', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('Feature_Old', models.CharField(blank=True, max_length=1000, null=True, verbose_name='مقدار قدیمی قابلیت')),
                ('Feature_New', models.CharField(blank=True, max_length=1000, null=True, verbose_name='مقدار جدید قابلیت')),
                ('FeatureCode', models.CharField(blank=True, max_length=10, verbose_name='کد ویژگی')),
                ('ActionType', models.CharField(choices=[('D', 'حذف'), ('E', 'ویرایش'), ('A', 'افزودن')], max_length=1, verbose_name='نوع عملیات')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamCorpFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatorUserName', models.CharField(max_length=150, null=True, verbose_name='ایجاد شده توسط')),
                ('LastModifierUserName', models.CharField(max_length=150, null=True, verbose_name='ویرایش شده توسط')),
                ('CreateDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('ModifyDate', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('CorpCode', models.CharField(max_length=3, verbose_name='نام شرکت')),
                ('YearNumber', models.PositiveSmallIntegerField(verbose_name='سال')),
                ('FeatureCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamCorpFeatureFeatureCode', to='TeamFeature.teamfeature', verbose_name='قابلیت')),
            ],
            options={
                'verbose_name': 'قابلیت تیم شرکت',
                'verbose_name_plural': 'قابلیت های تیم ها و شرکت ها ',
            },
        ),
    ]
