# Generated by Django 4.0.1 on 2024-12-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamFeature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamfeature',
            name='Importance',
            field=models.PositiveSmallIntegerField(choices=[('متوسط', 1), ('بالا', 2), ('خیلی بالا', 3)], default=1, null=True, verbose_name='میزان اهمیت'),
        ),
    ]
